In [1]:
import numpy as np

def fromfunction(n):
    arr = np.zeros((n,n)) 
    
    for i in range(0,n):
        for j in range(0,n):
            if i == j: 
                arr[i][j] = n
            else:
                arr[i][j] = (i+1) + (j+1)
    
    return arr        
    
n = int(input("Enter the value of n for the nxn matrix: "))
arr = fromfunction(n)
print(arr)

[[4. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 4. 7.]
 [5. 6. 7. 4.]]
